export enum AppEvent {
  RUN_SOUP_EXTRACTOR = 'RUN_SOUP_EXTRACTOR',
  RUN_SUMMARIZER = 'RUN_SUMMARIZER',
  RUN_SITEMAP = 'RUN_SITEMAP',
  RUN_INTERNAL_LINKS = 'RUN_INTERNAL_LINKS',
  RUN_KEYWORD = 'RUN_KEYWORD',
  RUN_LIGHTHOUSE = 'RUN_LIGHTHOUSE',
  RUN_OBSERVATORY = 'RUN_OBSERVATORY',

  EXTRACTION_FINISHED = 'EXTRACTION_FINISHED',
  SUMMARIZER_FINISHED = 'SUMMARIZER_FINISHED',
  SITEMAP_FINISHED = 'SITEMAP_FINISHED',
  KEYWORD_FINISHED = 'KEYWORD_FINISHED',
  LIGHTHOUSE_FINISHED = 'LIGHTHOUSE_FINISHED',
  OBSERVATORY_FINISHED = 'OBSERVATORY_FINISHED',
}
