version: '3.7'

services:
  postgres:
    image: postgres:14
    restart: always
    container_name: postgres
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - seo_tools
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root

  adminer:
    image: adminer
    restart: always
    ports:
      - 8099:8080
    networks:
      - seo_tools

  server:
    build: ./server
    container_name: server
    depends_on:
      - postgres
      - redis
    command: yarn start
    networks:
      - seo_tools
    env_file:
      - ./server/.env
    ports:
      - 4030:3000
    restart: always

  admin:
    build: ./admin
    container_name: admin
    ports:
      - 6080:80
    networks:
      - seo_tools
    depends_on:
      - postgres
      - redis
      - server

  redis:
    image: redis
    container_name: redis
    restart: always
    networks:
      - seo_tools
    volumes:
      - cache:/data
    ports:
      - 6380:6379

volumes:
  data:
    driver: local
  cache:
    driver: local

networks:
  seo_tools:
