export enum AppEvent {
  RUN_SOUP_EXTRACTOR = 'RUN_SOUP_EXTRACTOR',
  RUN_SUMMARIZER = 'RUN_SUMMARIZER',
  RUN_SITEMAP = 'RUN_SITEMAP',
  RUN_INTERNAL_LINKS = 'RUN_INTERNAL_LINKS',
  RUN_KEYWORD = 'RUN_KEYWORD',
  RUN_LIGHTHOUSE = 'RUN_LIGHTHOUSE',
  RUN_OBSERVATORY = 'RUN_OBSERVATORY',

  EXTRACTION_STATUS_CHANGED = 'EXTRACTION_STATUS_CHANGED',
  SUMMARIZER_STATUS_CHANGED = 'SUMMARIZER_STATUS_CHANGED',
  SITEMAP_STATUS_CHANGED = 'SITEMAP_STATUS_CHANGED',
  KEYWORD_STATUS_CHANGED = 'KEYWORD_STATUS_CHANGED',
  LIGHTHOUSE_STATUS_CHANGED = 'LIGHTHOUSE_STATUS_CHANGED',
  OBSERVATORY_STATUS_CHANGED = 'OBSERVATORY_STATUS_CHANGED',
}
